### ISSUE TITLE
Support hotplug feature

### ISSUE THREAD

**Issue by i-yxd** [dcuddeback/libusb-sys#10]
Hotplug feature is supported since v1.0.16 of libusb.

**Comment by richo** [comment]
I just opened #11 which should add hotplug support. I will add it to the -rs crate as well to give nicer support.

**Comment by blandger** [comment]
Unfortunately project looks like abandoned , if PR-s are not reviewed and not considered for merge... :(

**Comment by richo** [comment]
I think that's correct, although for what it's worth the code I added in #11 does not appear to work for me, and I was never able to diagnose why (it might just be my peripheral?).

I would be happy to maintain this crate if @dcuddeback would prefer, although I am not an expert in libusb so it would be more of a steward than a technical leader.

**Comment by blandger** [comment]
I have similar problem. Couple of methods are missing and they use a callbacks, which are tricky as I suppose.
I'm trying to figure out how to use them - https://stackoverflow.com/questions/41081240/idiomatic-callbacks-in-rust

Probably, you can try to write simple example and put it into PR, so may be someone else could check you code as well.

**Comment by richo** [comment]
So roughly speaking that's what #11 is, the smallest possible bridge to allow registering rust callbacks (but it would want some nicer high level code in the `libusb` crate. It has been a while since I thought about this but from memory invoking the code in #11 didn't work, but neither did a native C implementation of the same thing so I wrote it off to either my system or my peripheral having issues. From memory there are some constraints with hotplug in libusb.

**Comment by richo** [comment]
I can try to find if I still have that prototype somewhere but I'm not sure the chances are good.

**Comment by dcuddeback** [comment]
Fixed by #11.
